import { KiteConnect,KiteTicker } from 'kiteconnect';
import type { Connect,HistoricalData,Instrument,Tick,Ticker } from 'kiteconnect';
import { config,kiteConfigured } from './config.js';
import { loadSession,saveSession } from './session-store.js';
import { loadWatchlist } from './watchlist.js';
import type { Candle,LiveQuote,Session } from './types.js';
import { analyse } from './indicators.js';
import { sendPush } from './push.js';

type Cached={expires:number,candles:Candle[]};
class KiteService{
  private client:Connect|null=null;private ticker:Ticker|null=null;private session:Session|null=null;
  private symbols=new Map<string,Instrument>();private tokenSymbols=new Map<number,string>();private quotes=new Map<string,LiveQuote>();private candles=new Map<string,Candle[]>();private lastDayVolume=new Map<string,number>();private cache=new Map<string,Cached>();private lastSignal=new Map<string,string>();
  private historyQueue:Promise<unknown>=Promise.resolve();private connected=false;private unresolved:string[]=[];
  async init(){if(!kiteConfigured)return;const client=new KiteConnect({api_key:config.KITE_API_KEY!});this.client=client;const stored=await loadSession();const token=config.KITE_ACCESS_TOKEN??stored?.accessToken;if(token){this.session=stored??{accessToken:token,userId:'env',createdAt:new Date().toISOString()};client.setAccessToken(token);await this.start().catch(error=>console.error('Kite startup failed:',error))}}
  loginUrl(){if(!this.client)throw new Error('Kite credentials are not configured');return this.client.getLoginURL()}
  async authenticate(requestToken:string){if(!this.client)throw new Error('Kite credentials are not configured');const result=await this.client.generateSession(requestToken,config.KITE_API_SECRET!);this.session={accessToken:result.access_token,userId:result.user_id,createdAt:new Date().toISOString()};await saveSession(this.session);this.client.setAccessToken(result.access_token);await this.start();return{userId:result.user_id}}
  private async start(){await this.resolveInstruments();this.connectTicker()}
  private async resolveInstruments(){const [instruments,watchlist]=await Promise.all([this.client!.getInstruments(),loadWatchlist()]);const master=new Map(instruments.map(x=>[`${x.exchange}:${x.tradingsymbol}`,x]));this.symbols.clear();this.tokenSymbols.clear();this.unresolved=[];for(const symbol of watchlist){const instrument=master.get(symbol);if(!instrument){this.unresolved.push(symbol);continue}this.symbols.set(symbol,instrument);this.tokenSymbols.set(Number(instrument.instrument_token),symbol)}}
  private connectTicker(){if(!this.session||!config.KITE_API_KEY)return;this.ticker?.disconnect();const ticker=new KiteTicker({api_key:config.KITE_API_KEY,access_token:this.session.accessToken});this.ticker=ticker;ticker.autoReconnect(true,300,5);ticker.on('connect',()=>{this.connected=true;const tokens=[...this.tokenSymbols.keys()];for(let i=0;i<tokens.length;i+=1000){const batch=tokens.slice(i,i+1000);ticker.subscribe(batch);ticker.setMode(ticker.modeFull,batch)}});ticker.on('ticks',ticks=>this.onTicks(ticks));ticker.on('disconnect',()=>{this.connected=false});ticker.on('error',error=>console.error('Kite ticker:',error.message));ticker.connect()}
  private onTicks(ticks:Tick[]){for(const tick of ticks){const symbol=this.tokenSymbols.get(tick.instrument_token);if(!symbol)continue;const full=tick as Tick&{change?:number;volume_traded?:number;exchange_timestamp?:Date};const time=full.exchange_timestamp?.getTime()??Date.now(),volume=full.volume_traded??0;this.quotes.set(symbol,{symbol,instrumentToken:tick.instrument_token,price:tick.last_price,changePercent:full.change??0,dayVolume:volume,updatedAt:time});this.addLiveCandle(symbol,time,tick.last_price,volume)}}
  private addLiveCandle(symbol:string,time:number,price:number,dayVolume:number){const bucket=Math.floor(time/300000)*300000,list=this.candles.get(symbol)??[],current=list.at(-1),previous=this.lastDayVolume.get(symbol),volumeDelta=previous===undefined||dayVolume<previous?0:dayVolume-previous;this.lastDayVolume.set(symbol,dayVolume);if(!current||current.time!==bucket){if(current)this.evaluateClosedCandle(symbol,current);list.push({time:bucket,open:price,high:price,low:price,close:price,volume:volumeDelta});if(list.length>120)list.shift()}else{current.high=Math.max(current.high,price);current.low=Math.min(current.low,price);current.close=price;current.volume+=volumeDelta}this.candles.set(symbol,list)}
  private evaluateClosedCandle(symbol:string,closed:Candle){const cached=this.cache.get(symbol);if(!cached)return;const candles=cached.candles.filter(x=>x.time<closed.time).concat(closed).slice(-100),result=analyse(symbol,candles);if(result.signal==='WATCH')return;const key=`${result.signal}:${Math.round(result.price*20)/20}`;if(this.lastSignal.get(symbol)===key)return;this.lastSignal.set(symbol,key);void sendPush(`${result.signal} · ${symbol}`,`₹${result.price.toFixed(2)} · Score ${result.score>0?'+':''}${result.score} · Vol ${result.volumeRatio.toFixed(1)}×`,{symbol,signal:result.signal}).catch(error=>console.error('Expo push failed:',error))}
  private queued<T>(task:()=>Promise<T>):Promise<T>{const run=this.historyQueue.then(async()=>{await new Promise(r=>setTimeout(r,350));return task()});this.historyQueue=run.catch(()=>undefined);return run}
  async historical(symbol:string,limit=100):Promise<Candle[]>{if(!this.client||!this.session)throw new Error('Zerodha session is not connected');const instrument=this.symbols.get(symbol);if(!instrument)throw new Error(`Unknown or unavailable instrument: ${symbol}`);const cached=this.cache.get(symbol);if(cached&&cached.expires>Date.now())return cached.candles.slice(-limit);const to=new Date(),from=new Date(to.getTime()-10*24*60*60*1000);const rows=await this.queued(()=>this.client!.getHistoricalData(instrument.instrument_token,'5minute',from,to));const candles=rows.map(this.toCandle);const live=this.candles.get(symbol)?.at(-1);if(live&&live.time>(candles.at(-1)?.time??0))candles.push(live);this.cache.set(symbol,{expires:Date.now()+30_000,candles});return candles.slice(-Math.min(limit,500))}
  private toCandle=(x:HistoricalData):Candle=>({time:new Date(x.date).getTime(),open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume});
  status(){return{configured:kiteConfigured,authenticated:Boolean(this.session),streamConnected:this.connected,resolvedSymbols:this.symbols.size,unresolvedSymbols:this.unresolved.length,unresolvedSample:this.unresolved.slice(0,20),lastTickAt:Math.max(0,...[...this.quotes.values()].map(x=>x.updatedAt))||null}}
  getQuotes(){return[...this.quotes.values()]}
}
export const kite=new KiteService();
