import { KiteConnect,KiteTicker } from 'kiteconnect';
import type { Connect,HistoricalData,Instrument,Tick,Ticker } from 'kiteconnect';
import { config,kiteConfigured } from './config.js';
import { clearSession,loadSession,saveSession } from './session-store.js';
import { loadWatchlist } from './watchlist.js';
import type { Candle,LiveQuote,Session } from './types.js';
import { analyse } from './indicators.js';
import { sendPush } from './push.js';

type Cached={expires:number,candles:Candle[]};
class KiteService{
  private client:Connect|null=null;private ticker:Ticker|null=null;private session:Session|null=null;
  private symbols=new Map<string,Instrument>();private tokenSymbols=new Map<number,string>();private quotes=new Map<string,LiveQuote>();private candles=new Map<string,Candle[]>();private lastDayVolume=new Map<string,number>();private cache=new Map<string,Cached>();private lastSignal=new Map<string,string>();
  private historyQueue:Promise<unknown>=Promise.resolve();private queueDepth=0;private connected=false;private unresolved:string[]=[];private sessionError:string|null=null;private batchRunning=false;
  async init(){if(!kiteConfigured)return;const client=new KiteConnect({api_key:config.KITE_API_KEY!});this.client=client;const stored=await loadSession();const token=stored?.accessToken??config.KITE_ACCESS_TOKEN;if(token){this.session=stored??{accessToken:token,userId:'env',createdAt:new Date().toISOString()};client.setAccessToken(token);await this.start().catch(error=>{if(this.isAuthError(error))void this.invalidateSession('Kite session expired');else console.error('Kite startup failed:',error)})}}
  loginUrl(){if(!this.client)throw new Error('Kite credentials are not configured');return this.client.getLoginURL()}
  async authenticate(requestToken:string){if(!this.client)throw new Error('Kite credentials are not configured');const result=await this.client.generateSession(requestToken,config.KITE_API_SECRET!);this.session={accessToken:result.access_token,userId:result.user_id,createdAt:new Date().toISOString()};this.sessionError=null;await saveSession(this.session);this.client.setAccessToken(result.access_token);await this.start();return{userId:result.user_id}}
  private async start(){await this.resolveInstruments();this.connectTicker()}
  private async resolveInstruments(){const [instruments,watchlist]=await Promise.all([this.client!.getInstruments(),loadWatchlist()]);const master=new Map(instruments.map(x=>[`${x.exchange}:${x.tradingsymbol}`,x]));this.symbols.clear();this.tokenSymbols.clear();this.unresolved=[];for(const symbol of watchlist){const instrument=master.get(symbol);if(!instrument){this.unresolved.push(symbol);continue}this.symbols.set(symbol,instrument);this.tokenSymbols.set(Number(instrument.instrument_token),symbol)}}
  private connectTicker(){if(!this.session||!config.KITE_API_KEY)return;this.ticker?.disconnect();const ticker=new KiteTicker({api_key:config.KITE_API_KEY,access_token:this.session.accessToken});this.ticker=ticker;ticker.autoReconnect(true,300,5);ticker.on('connect',()=>{this.connected=true;this.sessionError=null;const tokens=[...this.tokenSymbols.keys()];for(let i=0;i<tokens.length;i+=1000){const batch=tokens.slice(i,i+1000);ticker.subscribe(batch);ticker.setMode(ticker.modeFull,batch)}});ticker.on('ticks',ticks=>this.onTicks(ticks));ticker.on('disconnect',()=>{this.connected=false});ticker.on('error',error=>{if(this.isAuthError(error))void this.invalidateSession('Kite rejected the access token');else console.error('Kite ticker:',error.message)});ticker.connect()}
  private isAuthError(error:unknown){const value=error as {message?:string;statusCode?:number;status?:number;error_type?:string};return value?.statusCode===403||value?.status===403||value?.error_type==='TokenException'||/\b403\b|tokenexception|access token|session expired/i.test(value?.message??'')}
  private async invalidateSession(reason:string){if(!this.session&&this.sessionError)return;this.sessionError=reason;this.connected=false;this.session=null;this.ticker?.autoReconnect(false,300,0);this.ticker?.disconnect();this.ticker=null;await clearSession();console.error(`Kite session invalidated: ${reason}`)}
  private onTicks(ticks:Tick[]){for(const tick of ticks){const symbol=this.tokenSymbols.get(tick.instrument_token);if(!symbol)continue;const full=tick as Tick&{change?:number;volume_traded?:number;exchange_timestamp?:Date};const time=full.exchange_timestamp?.getTime()??Date.now(),volume=full.volume_traded??0;this.quotes.set(symbol,{symbol,instrumentToken:tick.instrument_token,price:tick.last_price,changePercent:full.change??0,dayVolume:volume,updatedAt:time});this.addLiveCandle(symbol,time,tick.last_price,volume)}}
  private addLiveCandle(symbol:string,time:number,price:number,dayVolume:number){const bucket=Math.floor(time/300000)*300000,list=this.candles.get(symbol)??[],current=list.at(-1),previous=this.lastDayVolume.get(symbol),volumeDelta=previous===undefined||dayVolume<previous?0:dayVolume-previous;this.lastDayVolume.set(symbol,dayVolume);if(!current||current.time!==bucket){if(current)this.evaluateClosedCandle(symbol,current);list.push({time:bucket,open:price,high:price,low:price,close:price,volume:volumeDelta});if(list.length>120)list.shift()}else{current.high=Math.max(current.high,price);current.low=Math.min(current.low,price);current.close=price;current.volume+=volumeDelta}this.candles.set(symbol,list)}
  private evaluateClosedCandle(symbol:string,closed:Candle){const cached=this.cache.get(symbol);if(!cached)return;const candles=cached.candles.filter(x=>x.time<closed.time).concat(closed).slice(-100),result=analyse(symbol,candles);if(result.signal==='WATCH'||(result.changePercent>config.SCAN_MIN_CHANGE&&result.changePercent<config.SCAN_MAX_CHANGE))return;const key=`${result.signal}:${Math.round(result.price*20)/20}`;if(this.lastSignal.get(symbol)===key)return;this.lastSignal.set(symbol,key);void sendPush(`${result.signal} · ${symbol}`,`₹${result.price.toFixed(2)} · Day ${result.changePercent>0?'+':''}${result.changePercent.toFixed(2)}% · Score ${result.score>0?'+':''}${result.score}`,{symbol,signal:result.signal}).catch(error=>console.error('Expo push failed:',error))}
  private queued<T>(task:()=>Promise<T>):Promise<T>{if(this.queueDepth>=64)throw new Error('Market data queue is busy; retry shortly');this.queueDepth++;const run=this.historyQueue.then(async()=>{await new Promise(r=>setTimeout(r,350));return task()});this.historyQueue=run.catch(()=>undefined);return run.finally(()=>{this.queueDepth--})}
  async historical(symbol:string,limit=100):Promise<Candle[]>{if(!this.client||!this.session)throw new Error(this.sessionError??'Zerodha session is not connected');const instrument=this.symbols.get(symbol);if(!instrument)throw new Error(`Unknown or unavailable instrument: ${symbol}`);const cached=this.cache.get(symbol);if(cached&&cached.expires>Date.now())return cached.candles.slice(-limit);const to=new Date(),from=new Date(to.getTime()-10*24*60*60*1000);try{const rows=await this.queued(()=>this.client!.getHistoricalData(instrument.instrument_token,'5minute',from,to));const candles=rows.map(this.toCandle);const live=this.candles.get(symbol)?.at(-1);if(live&&live.time>(candles.at(-1)?.time??0))candles.push(live);this.cache.set(symbol,{expires:Date.now()+30_000,candles});return candles.slice(-Math.min(limit,500))}catch(error){if(this.isAuthError(error))await this.invalidateSession('Kite session expired');throw error}}
  async scan(symbols:string[]){if(this.batchRunning)throw new Error('A market scan is already running');this.batchRunning=true;try{const data:ReturnType<typeof analyse>[]=[],failed:{symbol:string;error:string}[]=[];for(const symbol of [...new Set(symbols)]){try{data.push(analyse(symbol,await this.historical(symbol,100)))}catch(error){failed.push({symbol,error:error instanceof Error?error.message:'Market data unavailable'});if(!this.session)break}}return{data,failed}}finally{this.batchRunning=false}}
  private toCandle=(x:HistoricalData):Candle=>({time:new Date(x.date).getTime(),open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume});
  status(){return{configured:kiteConfigured,authenticated:Boolean(this.session)&&!this.sessionError,streamConnected:this.connected,resolvedSymbols:this.symbols.size,unresolvedSymbols:this.unresolved.length,unresolvedSample:this.unresolved.slice(0,20),lastTickAt:Math.max(0,...[...this.quotes.values()].map(x=>x.updatedAt))||null,sessionError:this.sessionError,queueDepth:this.queueDepth,scanRunning:this.batchRunning}}
  getQuotes(){return[...this.quotes.values()]}
}
export const kite=new KiteService();
